name: Test Docker Build

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'docker-entrypoint.sh'
      - '.dockerignore'
      - '.github/workflows/test-docker.yml'
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'docker-entrypoint.sh'
      - '.dockerignore'

jobs:
  test-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Validate Docker Compose
        run: docker compose config --quiet
      
      - name: Run Docker implementation tests
        run: |
          chmod +x test-docker-implementation.sh
          ./test-docker-implementation.sh
      
      - name: Test Docker build (syntax only, no full build)
        run: |
          # This validates Dockerfile syntax without full build
          docker build --help
          docker buildx build --dry-run . || true
          
          # Check that base image exists
          docker pull nvidia/cuda:12.8.0-runtime-ubuntu24.04 || echo "Base image check skipped (requires NVIDIA registry access)"
      
      - name: Validate shell scripts
        run: |
          bash -n docker-entrypoint.sh
          bash -n docker-quickstart.sh
          test -x docker-entrypoint.sh
          test -x docker-quickstart.sh
